[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.flit.metadata]
module = "pycobolt"
author = "Cobolt Lasers"
home-page = "https://hubner-photonics.com"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"
